### ISSUE TITLE
Docs link at website leads to 404 page

### ISSUE THREAD

**Issue by Serpentarius13** [official-stockfish/stockfish-web#32]
### Describe the issue

Docs link at https://stockfishchess.org/ leads to a 404 page.

### Expected behavior

I believe it should redirect to https://disservin.github.io/stockfish-docs/, not https://disservin.github.io/stockfish-docs/pages/Home.html

### Steps to reproduce

Go to website
Click the `docs` link in navbar

### Operating system

All

### Stockfish version

-

**Comment by Disservin** [comment]
Thanks.. i moved it to this repo, because it's not really related to other one.
