### ISSUE TITLE
Speedtest command not added to website docs

### ISSUE THREAD

**Issue by jalpp** [official-stockfish/stockfish-web#46]
https://github.com/official-stockfish/Stockfish/wiki/UCI-&-Commands

speedtest info here is missing from the main docs.

I can work on it if you don't mind

**Comment by dav1312** [comment]
The website docs are here https://github.com/official-stockfish/docs
Ideally they should be updated automatically on a regular basis
(CC @Disservin )

**Comment by Disservin** [comment]
I've updated the docs mirror.
